package br.com.sap.view;

import br.com.sap.dao.ModuloConexao;
import java.sql.*;
import javax.swing.JOptionPane;
import br.com.sap.model.ValidMail;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;

public class TelaLogin extends javax.swing.JFrame {
    
    // usando variável de conexão do DAL
    Connection conexao = null;

    // Criando variáveis especiais para conexão do banco
    //Prepareted Statement e Resultset são frameworks do pacote java.sql
    // e servem para preparar e executar as instruções SQL
    PreparedStatement pst = null;
    ResultSet rs = null;
    String sql = "select * from usuario where email=? and senha=?";
    
                       
    // criando o método logar
    public void logar() {
                
       String email =  txtMail.getText();
       
       if (ValidMail.isValidEmailAddress(email)) {
                           
        try {
            // as linhas abaixo preparam a consulta ao banco em função do que foi digitado nas caixas de texto
            // o ? é substituido pelo conteúdo das variáveis
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtMail.getText());
            pst.setString(2, txtSenha.getText());
            
                       
            // a linha abaixo executa a consulta ao banco de dados
            rs = pst.executeQuery();
            
            // se existir usuário e senha correspondente
            if (rs.next()) {
                    
                TelaPrincipal principal = new TelaPrincipal();
                principal.setVisible(true);
                    
                // fechando a tela de login ao logar
                    this.dispose();

                // fechando a conexão com o banco de dados
                conexao.close();
            } else {
                JOptionPane.showMessageDialog(this, "Usuário e ou senha inválido(s)");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    } else {
           JOptionPane.showMessageDialog(this, "O e-mail informado não possui um formato válido","E-mail Inválido",JOptionPane.ERROR_MESSAGE);
           this.setVisible(true);
       }
    }    
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    
        conexao = ModuloConexao.conector();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogoLogin = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnLogar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISDEF - Tela de Login");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sap/icones/logo (1).png"))); // NOI18N
        getContentPane().add(lblLogoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 120));

        lblMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMail.setText("E-Mail");
        getContentPane().add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 60, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        txtMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 310, -1));

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 310, -1));

        btnLogar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogar.setText("Logar");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        setSize(new java.awt.Dimension(500, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        // Chamando o método logar
    //LoginControler logar = new LoginControler();
    //logar.logar();
    logar();  
    }//GEN-LAST:event_btnLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogoLogin;
    private javax.swing.JLabel lblMail;
    public static javax.swing.JTextField txtMail;
    public static javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
